### ISSUE TITLE
Questions about median scaling

### ISSUE THREAD

**Issue by jikerWRN** [microsoft/S2R-DepthNet#10]
Hi, as shown in the code, the last activation function is tanh,  the depth image used for surpervised is scaled to 0-1 in training, and the output of network will scale to 0~80m (kitti) in testing. 

```
# training 
if self.dataset.upper() == 'KITTI' or self.dataset.upper() == 'VKITTI':
	#print("Using outdoor scene transform.")
	arr_depth = np.array(depth, dtype=np.float32)
	arr_depth[arr_depth>8000.0]=8000.0
	arr_depth /= 8000.0   # cm -> m 
	arr_depth[arr_depth<0.0] = 0.0

# testing
pred_depth_np += 1.0
pred_depth_np /= 2.0
pred_depth_np *= 80.0
```

I know it based on previous work, but i am curious why scaling instead of directly regressing to the real depth value? Will it bring performance improvements?

Thanks in advance!

**Comment by Xt-Chen** [comment]
This code is not median scaling. During the training process, we linearly map the ground truth depth (0~80m) to (-1~1). The purpose of this operation is to help the training process to be more stable.

**Comment by jikerWRN** [comment]
Does this have any effect on accuracy？

**Comment by jikerWRN** [comment]
By the way, could you explain what is the median scaling and why needs the operation? Thanks!

**Comment by Xt-Chen** [comment]
Since the depth predicted by our method is defined up to a scale factor, for evaluation we multiply the predicted
depth maps by a scalar that matches the median with the ground truth.

**Comment by jikerWRN** [comment]
Ok, i got it, thanks!
