### ISSUE TITLE
Cuda out of memory in test.py.

### ISSUE THREAD

**Issue by yangbaoquan** [microsoft/S2R-DepthNet#13]
https://github.com/microsoft/S2R-DepthNet/blob/bf2c5d914f0f4bfc976a469460a04480179eb34f/test.py#L274

If you encounter any problems, you can try the following code: 

```python
pred_depth = pred_depth.cpu().detach().numpy()
pred_depth_np = np.squeeze(pred_depth)
```

**Comment by wangzizhe** [comment]
@yangbaoquan I've been stuck in this "CUDA out of memory" issue and this works for me. Thanks a lot!
