### ISSUE TITLE
How to visualize the depth map picture?

### ISSUE THREAD

**Issue by wangzizhe** [microsoft/S2R-DepthNet#14]
Hi, I have a question about how to visualize the depth map picture as you showed in your result? Thanks in advance.

**Comment by Xt-Chen** [comment]
Hi, you can use the 'colormap' function in utils.py to visualize the depth map.

**Comment by Xt-Chen** [comment]
Or you also can use the following code to visualize the depth map.

mpimg.imsave(args.out_dir+'/pred_depth_%02d.png'%i, pred_depth_np, cmap="jet")

**Comment by wangzizhe** [comment]
Thanks a lot. Maybe it's a good idea to merge it to the code, so everybody who run the code will have an intuitive understanding of how this model works. Have a good day 💯
