### ISSUE TITLE
Pretrained model link error

### ISSUE THREAD

**Issue by Arbitersc** [microsoft/S2R-DepthNet#18]
I want to get the pretrained model.But, when i clicked the link, i got this:

> Not fully secure

so, is there any wrong ?
i see the the url is [https://1drv.ms/u/s!AlwUS_9Kpa8qgkb9ldQbMAMgNd_I?e=aX2PWY](https://1drv.ms/u/s!AlwUS_9Kpa8qgkb9ldQbMAMgNd_I?e=aX2PWY)

**Comment by wangzizhe** [comment]
![image](https://user-images.githubusercontent.com/52628547/123924351-2d150a80-d98a-11eb-99ee-610f87a0b68a.png)
This link works for me. Maybe you can try login to your OneDrive.

**Comment by Arbitersc** [comment]
> ![image](https://user-images.githubusercontent.com/52628547/123924351-2d150a80-d98a-11eb-99ee-610f87a0b68a.png)
> This link works for me. Maybe you can try login to your OneDrive.

thank you. I got it.
