### ISSUE TITLE
question about pretain_model

### ISSUE THREAD

**Issue by xuchen-dev** [microsoft/S2R-DepthNet#3]
hi! i cant download the pretrain model you provide , would please send me by email   947628380@qq.com
or other ways convenient to you

**Comment by wangzizhe** [comment]
I also failed downloading them together using Microsoft Edge, then I switched to Google Chrome and downloaded outdoor pretrained models one by one, succeed. Maybe you can have a try :)

**Comment by xuchen-dev** [comment]
i even cant open the link    could send  thankyou  very much
![image](https://user-images.githubusercontent.com/79962968/121981689-b7714200-cdc0-11eb-8731-4aceeac7c2bc.png)

**Comment by wangzizhe** [comment]
The files are too big to send to you via email, what it shows when you click the link? Maybe you should try login to your OneDrive account. Then it will be listed in _shared files_ in your account.

**Comment by xuchen-dev** [comment]
onedrive.live.com  in china is can't open    
![image](https://user-images.githubusercontent.com/79962968/122140346-9cb0d300-ce7d-11eb-831a-f0492c38ae63.png)
![image](https://user-images.githubusercontent.com/79962968/122140354-a20e1d80-ce7d-11eb-86ea-c6735df4f00f.png)
i just need the shared struct encoder pretrain model，because in the program there is nowhere train the STE encoder
if have the struct decoder would be better
can you shared by baidunetdisk（百度云网盘）

**Comment by wangzizhe** [comment]
sent via email :)

**Comment by xuchen-dev** [comment]
thank you very much
