### ISSUE TITLE
module "net_mask" from "test.py" | no module named "net_mask"

### ISSUE THREAD

**Issue by wangzizhe** [microsoft/S2R-DepthNet#5]
Hi, when I run `test.py` there come an error `no module named "net_mask"`. I found this code is in line 23 `import net_mask`. I didn't find any information about the module `net_mask`, could you please explain what this module is and how can I prevent this error? Thanks a lot in advance.

**Comment by Xt-Chen** [comment]
Thank you, I have corrected this error in the latest version.
