### ISSUE TITLE
cam_intrin | Camera info does not exist | Where to find?

### ISSUE THREAD

**Issue by wangzizhe** [microsoft/S2R-DepthNet#6]
Hi, I want to test it but facing an issue.

![image](https://user-images.githubusercontent.com/52628547/122037437-ded20a00-cdd4-11eb-9146-0207420777b7.png)

No data of camera info are loaded.

In `loaddata.py`, there are 4 kinds of data which should be loaded: 

- `l_rgb`

- `r_rgb`

- `cam_intrin`

- `depth`

from KITTI dataset, for example: `2011_09_26_drive_0015_sync`, the file structure is as following:
```
2011_09_26_drive_0015_sync
│   image_00
│   image_01    
│   image_02
│   image_03
│   oxts
│   velodyne_points

```

as the `test.txt` under `S2R-DepthNet\datasets\kitti` shows, 

![image](https://user-images.githubusercontent.com/52628547/122037343-c5c95900-cdd4-11eb-9358-783b890339e0.png)

`.png` files from `images_02` = `l_rgb`
`.png` files from `image_03` = `r_rgb`
`.bin`  files from `velodyne_points` = `depth`

The files in `image_00` and `image_01` are grayscale image. The files in `oxts` seems to be GPU and IMU data. 

**Then where can I find the files which are relevant to camera infos `(cam_intrin)`?**

Thank a lot in advance :-)

**Comment by Xt-Chen** [comment]
Hi, in the test.txt under S2R-DepthNet\datasets\kitti, the third item of each line is 'cam_intrin', for example, '2011_09_26'. 
Thanks.

**Comment by wangzizhe** [comment]
understood, I need to download `Calibration` files from KITTI and put `calib_cam_to_cam.txt` under `2011_09_26`
thanks a lot 😄
