### ISSUE TITLE
TypeError:'int' object is not subscriptable during testing

### ISSUE THREAD

**Issue by wangzizhe** [microsoft/S2R-DepthNet#7]
Hi, during testing these is an error arised

> TypeError:'int' object is not subscriptable

![image](https://user-images.githubusercontent.com/52628547/122179178-8c9df100-ce87-11eb-9ad9-beef276f7795.png)

**Some codes of `transform.py` maybe need to be modified to fix this error. Could you please have a check of this issue?**

Thanks a lot in advance.

---

_My setup (for reference)_
![image](https://user-images.githubusercontent.com/52628547/122179490-df77a880-ce87-11eb-8ae2-0270c75ab577.png)

**Comment by Xt-Chen** [comment]
During the test, the outdoor scene image's size needs to be set to 192x640. As I wrote in the readme, you should set "--loadSize 192 640".

**Comment by wangzizhe** [comment]
solved, thx :-)
