### ISSUE TITLE
Question about vkitti dataset?

### ISSUE THREAD

**Issue by jikerWRN** [microsoft/S2R-DepthNet#8]
Hi, thanks for your good work!
There are two camera views in each sequences (Camera_0 and Camera_1), but i found the data file you used does not distinguish between Camera_0 and Camera_1, for example,
      rgb/0006/clone/00046.png depth/0006/clone/00046.png
      rgb/0006/clone/00073.png depth/0006/clone/00073.png
      rgb/0006/clone/00176.png depth/0006/clone/00176.png
I want to know which camera view you use in the experiment? And why don't use both of Camera_0 and Camera_1  data? It will provide more train data, right?
Another problem is how to divide the train, val and test datasets?
Thank you in advance！

**Comment by Xt-Chen** [comment]
Hi，vkitti dataset does not contain the two camera views. 
"Virtual KITTI contains 50 high-resolution monocular videos (21,260 frames) generated from five different virtual worlds in urban settings under different imaging and weather conditions".  For the details of the dataset, you can refer to the link below. https://europe.naverlabs.com/research/computer-vision/proxy-virtual-worlds-vkitti-1

**Comment by jikerWRN** [comment]
Thanks for your reply!
This may be because I downloaded vkitti 2 dataset and you are using vkitti 1.3.1.
